# Generated by Django 2.2 on 2020-07-31 15:31

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=250)),
                ('guess', models.CharField(max_length=150)),
                ('photograph', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('resume', models.TextField()),
                ('content', models.TextField()),
                ('facebookUrl', models.TextField(blank=True, null=True)),
                ('twitterUrl', models.TextField(blank=True, null=True)),
                ('whatsappUrl', models.TextField(blank=True, null=True)),
                ('mailUrl', models.TextField(blank=True, null=True)),
                ('coverImage', models.FileField(blank=True, null=True, upload_to=backend.models.articles_image_path)),
                ('articleImage', models.FileField(blank=True, null=True, upload_to=backend.models.articles_image_path)),
                ('cover', models.BooleanField(default=False)),
                ('mainMenu', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.UserProfile')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.UserProfile')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_date'],
            },
        ),
    ]
