# Generated by Django 2.2 on 2020-07-31 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='seo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.UserProfile')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.UserProfile')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MainMenuNavPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('picture1', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture2', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture3', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture4', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture5', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture6', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture7', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('picture8', models.FileField(blank=True, null=True, upload_to='mainmenunav')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.UserProfile')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.UserProfile')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_date'],
            },
        ),
    ]
