# Generated by Django 2.2 on 2020-05-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Catalog'),
        ),
    ]
