# Generated by Django 2.2 on 2020-07-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture1',
            new_name='accessory',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture2',
            new_name='bag',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture3',
            new_name='beauty',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture4',
            new_name='clothing',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture5',
            new_name='editorial',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture6',
            new_name='jewelery',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture7',
            new_name='lingerie',
        ),
        migrations.RenameField(
            model_name='mainmenunavpicture',
            old_name='picture8',
            new_name='shoes',
        ),
    ]
