# Generated by Django 2.2 on 2020-07-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200731_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variety', to='backend.Product'),
        ),
    ]
