# Generated by Django 2.2 on 2020-06-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200624_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Group',
            new_name='group',
        ),
    ]
