# Generated by Django 2.2 on 2020-07-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200624_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='picture',
            field=models.FileField(null=True, upload_to='catalogs'),
        ),
    ]
