# Generated by Django 2.2 on 2020-08-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200801_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
