# Generated by Django 2.2 on 2020-08-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200803_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='home',
            new_name='is_home',
        ),
    ]
