# Generated by Django 2.2 on 2020-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200803_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
